name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tarnza23/php-webapp1
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

