name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs1:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image DockerHub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tarnza23/php-webapp
        tags: latest ${{ github.sha }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

jobs2:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image Push To quay.io
      uses: redhat-actions/push-to-registry@v2
      with:
        image: tarnza23/php-webapp
        tags: latest ${{ github.sha }}
        registry: quay.io/tarnza23
        username: tarnza23
        password: ${{ secrets.REGISTRY_PASSWORD }}

